// 24/7 residency setup (opt-in). Honest scope: this configures AUTO-START +
// KEEPALIVE WHILE THE USER IS LOGGED IN (Windows Scheduled Task at-logon /
// macOS LaunchAgent / Linux systemd --user). True pre-login unattended startup
// needs extra steps (documented). Node built-ins only.
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { t } from "./i18n.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..");

/** Logical instance id → safe resource name, consistent across task/unit/logs. */
export function instanceId() {
  const raw = (process.env.DISCOPILOT_INSTANCE_ID ?? "default").trim();
  return /^[A-Za-z0-9._-]{1,64}$/.test(raw) ? raw : "default";
}

export function residencyName() {
  return `discopilot-${instanceId()}`;
}

/** Directory that holds copilot(.exe) so the resident process can find it (the
 *  Scheduled Task / launchd / systemd env has almost no PATH). */
function copilotDir() {
  const which = process.platform === "win32" ? "where" : "which";
  try {
    const out = execFileSync(which, ["copilot"], { encoding: "utf8" }).split(/\r?\n/)[0].trim();
    return out ? path.dirname(out) : "";
  } catch {
    return "";
  }
}

function gitDir() {
  const which = process.platform === "win32" ? "where" : "which";
  try {
    const out = execFileSync(which, ["git"], { encoding: "utf8" }).split(/\r?\n/)[0].trim();
    return out ? path.dirname(out) : "";
  } catch {
    return "";
  }
}

export async function setupResidency(lang) {
  if (process.platform === "win32") return setupWindows(lang);
  if (process.platform === "darwin") return setupMac(lang);
  if (process.platform === "linux") return setupLinux(lang);
  return;
}

// ---- Windows: Scheduled Task (at-logon keepalive, no admin) ----------------
function setupWindows(lang) {
  const name = residencyName();
  const node = process.execPath;
  const cop = copilotDir();
  const git = gitDir();
  const logDir = path.join(os.homedir(), ".discopilot", "logs");
  fs.mkdirSync(logDir, { recursive: true });
  const logFile = path.join(logDir, `${name}.log`);

  // A wrapper fixes PATH + HOME so copilot.exe resolves, then runs the bot.
  const wrapper = path.join(REPO_ROOT, "scripts", "run-bot.ps1");
  const wrapperBody = [
    "# Auto-generated by discopilot setup — starts the bot with a fixed environment.",
    "$ErrorActionPreference = 'Stop'",
    // Prepend the copilot + git dirs to the machine PATH so copilot.exe resolves
    // even under the minimal Scheduled-Task environment.
    `$env:PATH = '${cop};${git};' + $env:PATH`,
    "$env:HOME = $env:USERPROFILE",
    `Set-Location -LiteralPath '${REPO_ROOT}'`,
    `& '${node}' dist/index.js *>> '${logFile}'`,
  ].join("\r\n");
  fs.writeFileSync(wrapper, wrapperBody + "\r\n", "utf8");

  const psExe = path.join(process.env.SystemRoot || "C:\\Windows", "System32", "WindowsPowerShell", "v1.0", "powershell.exe");
  // Register with hardening: run at logon, restart on failure, no time limit,
  // start when available, and never spawn a second instance.
  const register = [
    "$ErrorActionPreference='Stop'",
    `$name='${name}'`,
    `$action=New-ScheduledTaskAction -Execute '${psExe}' -Argument '-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \"${wrapper}\"'`,
    "$trigger=New-ScheduledTaskTrigger -AtLogOn",
    "$settings=New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -MultipleInstances IgnoreNew",
    // Verify an existing task, if any, belongs to discopilot before replacing it.
    "$existing=Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue",
    "if($existing -and ($existing.Actions.Arguments -notlike '*run-bot.ps1*')){ throw \"A Scheduled Task named $name exists but is not discopilot's; refusing to replace it.\" }",
    "Register-ScheduledTask -TaskName $name -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null",
    "Start-ScheduledTask -TaskName $name",
    "Write-Output 'registered'",
  ].join("; ");

  execFileSync(psExe, ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", register], {
    stdio: "inherit",
  });
  console.log(t("residencyWin", lang) + name);
  console.log(
    lang === "zh"
      ? `  停止：schtasks /End /TN ${name}  ；移除：schtasks /Delete /TN ${name} /F  ；記錄：${logFile}`
      : `  Stop: schtasks /End /TN ${name}  ; Remove: schtasks /Delete /TN ${name} /F  ; Log: ${logFile}`
  );
}

// ---- macOS: LaunchAgent (login-only; experimental, unverified on real HW) ----
function setupMac(lang) {
  const name = residencyName();
  const label = `com.discopilot.${instanceId()}`;
  const node = process.execPath;
  const cop = copilotDir();
  const logDir = path.join(os.homedir(), ".discopilot", "logs");
  fs.mkdirSync(logDir, { recursive: true });
  const plistPath = path.join(os.homedir(), "Library", "LaunchAgents", `${label}.plist`);
  fs.mkdirSync(path.dirname(plistPath), { recursive: true });

  const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${esc(label)}</string>
  <key>ProgramArguments</key><array><string>${esc(node)}</string><string>dist/index.js</string></array>
  <key>WorkingDirectory</key><string>${esc(REPO_ROOT)}</string>
  <key>EnvironmentVariables</key><dict>
    <key>HOME</key><string>${esc(os.homedir())}</string>
    <key>PATH</key><string>${esc([cop, "/usr/local/bin", "/usr/bin", "/bin"].filter(Boolean).join(":"))}</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>${esc(path.join(logDir, name + ".log"))}</string>
  <key>StandardErrorPath</key><string>${esc(path.join(logDir, name + ".log"))}</string>
</dict></plist>
`;
  fs.writeFileSync(plistPath, plist, "utf8");
  try {
    execFileSync("plutil", ["-lint", plistPath], { stdio: "ignore" });
    const uid = String(process.getuid ? process.getuid() : "");
    try {
      execFileSync("launchctl", ["bootout", `gui/${uid}`, plistPath], { stdio: "ignore" });
    } catch {
      /* not loaded */
    }
    execFileSync("launchctl", ["bootstrap", `gui/${uid}`, plistPath], { stdio: "inherit" });
  } catch (e) {
    console.log((lang === "zh" ? "⚠️ launchd 載入未完成（實驗性）：" : "⚠️ launchd load incomplete (experimental): ") + (e && e.message));
  }
  console.log(t("residencyMac", lang) + plistPath);
}

// ---- Linux: systemd --user (login keepalive; pre-login needs linger) --------
function setupLinux(lang) {
  const name = residencyName();
  const node = process.execPath;
  const cop = copilotDir();
  const unitDir = path.join(os.homedir(), ".config", "systemd", "user");
  fs.mkdirSync(unitDir, { recursive: true });
  const unitPath = path.join(unitDir, `${name}.service`);
  const unit = `[Unit]
Description=discopilot (${name})
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${REPO_ROOT}
Environment=HOME=${os.homedir()}
Environment=PATH=${[cop, "/usr/local/bin", "/usr/bin", "/bin"].filter(Boolean).join(":")}
ExecStart=${node} dist/index.js
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
`;
  fs.writeFileSync(unitPath, unit, "utf8");
  try {
    execFileSync("systemctl", ["--user", "daemon-reload"], { stdio: "ignore" });
    execFileSync("systemctl", ["--user", "enable", "--now", `${name}.service`], { stdio: "inherit" });
  } catch (e) {
    console.log((lang === "zh" ? "⚠️ systemd 啟用未完成（實驗性）：" : "⚠️ systemd enable incomplete (experimental): ") + (e && e.message));
  }
  console.log(t("residencyLinux", lang) + unitPath);
  console.log(
    lang === "zh"
      ? "  提示：登入前也要常駐請執行 `loginctl enable-linger $USER`（可能需權限）。"
      : "  Note: for pre-login residency run `loginctl enable-linger $USER` (may need privileges)."
  );
}
